In [21]:
import pandas as pd

In [22]:
# Load both combined data sets
sets = pd.read_csv('../Data/combined_set_data.csv')
full_data = pd.read_csv('../Data/combined_full_data.csv')

In [28]:
# Identify the columns in full_data that are not in sets
static_columns = full_data.columns[~full_data.columns.isin(sets.columns)]

# Remove names that include "price" or 'release'
static_columns = static_columns[~static_columns.str.contains('price|release', case=False)]

# Remove views, viewsweek, upvotes, downvotes
static_columns = static_columns[~static_columns.str.contains('views|upvotes|downvotes', case=False)]

# static_columns

mask = full_data['time_pulled'] == max(full_data['time_pulled'])

# Add card_id, name, set_name, and set_code to static columns
choice_cols = static_columns.union(['card_id', 'name', 'set_name', 'set_code', 'rarity'])

static_data = full_data[mask][choice_cols]

static_data

,archetype,atk,attribute,banlist_goat,banlist_ocg,banlist_tcg,card_id,def,desc,desc_length,...,ocg_date,pend_desc,race,rarity,scale,set_code,set_name,subtype,tcg_date,type
0,K9,NaN,Spell,Not Banned,Not Banned,Not Banned,80181649,NaN,"When this card is activated: You can add 1 ""K9...",92,...,2025-03-22 00:00:00,NaN,Continuous,Starlight Rare,NaN,JUSH-EN040,Justice Hunters,Continuous Spell,2025-07-31 00:00:00,Spell Card
1,K9,NaN,Spell,Not Banned,Not Banned,Not Banned,80181649,NaN,"When this card is activated: You can add 1 ""K9...",92,...,2025-03-22 00:00:00,NaN,Continuous,Super Rare,NaN,JUSH-EN040,Justice Hunters,Continuous Spell,2025-07-31 00:00:00,Spell Card
2,Alien,NaN,Spell,Not Banned,Not Banned,Not Banned,34541863,NaN,"During each of your Standby Phases, put 1 A-Co...",16,...,2007-02-15 00:00:00,NaN,Continuous,Common,NaN,FOTB-EN043,Force of the Breaker,Continuous Spell,2007-05-16 00:00:00,Spell Card
3,Alien,NaN,Spell,Not Banned,Not Banned,Not Banned,64163367,NaN,Each time an A-Counter(s) is removed from play...,32,...,2007-07-21 00:00:00,NaN,Continuous,Common,NaN,GLAS-EN062,Gladiator's Assault,Continuous Spell,2007-11-14 00:00:00,Spell Card
4,Alien,NaN,Spell,Not Banned,Not Banned,Not Banned,91231901,NaN,Target 1 face-up monster on the field; send 1 ...,66,...,2016-07-09 00:00:00,NaN,Quick-Play,Common,NaN,INOV-EN063,Invasion: Vengeance,Quick-Play Spell,2016-11-03 00:00:00,Spell Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39199,Utopia,0.0,EARTH,Not Banned,Not Banned,Not Banned,18865703,2000.0,When this card is Normal or Special Summoned: ...,56,...,2012-11-17 00:00:00,NaN,Aqua,Rare,NaN,KICO-EN036,King's Court,Effect Monster,2013-01-25 00:00:00,Effect Monster
39200,Utopia,1900.0,LIGHT,Not Banned,Not Banned,Not Banned,76080032,0.0,"You can target 1 ""Number C39: Utopia Ray"" you ...",51,...,2011-11-19 00:00:00,NaN,Beast,Rare,NaN,ORCS-EN005,Order of Chaos,Effect Monster,2012-01-14 00:00:00,Effect Monster
39201,Utopia,1900.0,LIGHT,Not Banned,Not Banned,Not Banned,76080032,0.0,"You can target 1 ""Number C39: Utopia Ray"" you ...",51,...,2011-11-19 00:00:00,NaN,Beast,Common,NaN,SP14-EN004,Star Pack 2014,Effect Monster,2012-01-14 00:00:00,Effect Monster
39202,Utopia,1900.0,LIGHT,Not Banned,Not Banned,Not Banned,76080032,0.0,"You can target 1 ""Number C39: Utopia Ray"" you ...",51,...,2011-11-19 00:00:00,NaN,Beast,Starfoil Rare,NaN,SP14-EN004,Star Pack 2014,Effect Monster,2012-01-14 00:00:00,Effect Monster
39203,Utopia,1900.0,LIGHT,Not Banned,Not Banned,Not Banned,76080032,0.0,"You can target 1 ""Number C39: Utopia Ray"" you ...",51,...,2011-11-19 00:00:00,NaN,Beast,Common,NaN,YS13-EN018,Super Starter: V for Victory,Effect Monster,2012-01-14 00:00:00,Effect Monster

In [32]:
# Join static_data to sets
full = sets.merge(static_data, 
                  on=['card_id', 'name', 'set_name', 'set_code', 'rarity'], 
                  how='left')

full

,Unnamed: 0,card_id,name,set_name,rarity,rarity_code,price,set_code,num_printings,num_rarities,...,md_rarity,monster_desc,num_formats,ocg_date,pend_desc,race,scale,subtype,tcg_date,type
0,0.0,80181649,"""A Case for K9""",Justice Hunters,Starlight Rare,(StR),0.00,JUSH-EN040,2.0,2.0,...,Unknown,NaN,2.0,2025-03-22 00:00:00,NaN,Continuous,NaN,Continuous Spell,2025-07-31 00:00:00,Spell Card
1,1.0,80181649,"""A Case for K9""",Justice Hunters,Super Rare,(SR),0.00,JUSH-EN040,2.0,2.0,...,Unknown,NaN,2.0,2025-03-22 00:00:00,NaN,Continuous,NaN,Continuous Spell,2025-07-31 00:00:00,Spell Card
2,2.0,34541863,"""A"" Cell Breeding Device",Force of the Breaker,Common,(C),0.00,FOTB-EN043,1.0,1.0,...,Rare,NaN,6.0,2007-02-15 00:00:00,NaN,Continuous,NaN,Continuous Spell,2007-05-16 00:00:00,Spell Card
3,3.0,64163367,"""A"" Cell Incubator",Gladiator's Assault,Common,(C),0.00,GLAS-EN062,1.0,1.0,...,Common,NaN,6.0,2007-07-21 00:00:00,NaN,Continuous,NaN,Continuous Spell,2007-11-14 00:00:00,Spell Card
4,4.0,91231901,"""A"" Cell Recombination Device",Invasion: Vengeance,Common,(C),0.00,INOV-EN063,1.0,1.0,...,Super Rare,NaN,5.0,2016-07-09 00:00:00,NaN,Quick-Play,NaN,Quick-Play Spell,2016-11-03 00:00:00,Spell Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392543,NaN,18865703,ZW - Ultimate Shield,King's Court,Rare,(R),0.87,KICO-EN036,2.0,2.0,...,Common,NaN,5.0,2012-11-17 00:00:00,NaN,Aqua,NaN,Effect Monster,2013-01-25 00:00:00,Effect Monster
392544,NaN,76080032,ZW - Unicorn Spear,Order of Chaos,Rare,(R),0.00,ORCS-EN005,4.0,3.0,...,Common,NaN,5.0,2011-11-19 00:00:00,NaN,Beast,NaN,Effect Monster,2012-01-14 00:00:00,Effect Monster
392545,NaN,76080032,ZW - Unicorn Spear,Star Pack 2014,Common,(C),0.00,SP14-EN004,4.0,3.0,...,Common,NaN,5.0,2011-11-19 00:00:00,NaN,Beast,NaN,Effect Monster,2012-01-14 00:00:00,Effect Monster
392546,NaN,76080032,ZW - Unicorn Spear,Star Pack 2014,Starfoil Rare,(SFR),0.00,SP14-EN004,4.0,3.0,...,Common,NaN,5.0,2011-11-19 00:00:00,NaN,Beast,NaN,Effect Monster,2012-01-14 00:00:00,Effect Monster
392547,NaN,76080032,ZW - Unicorn Spear,Super Starter: V for Victory,Common,(C),0.00,YS13-EN018,4.0,3.0,...,Common,NaN,5.0,2011-11-19 00:00:00,NaN,Beast,NaN,Effect Monster,2012-01-14 00:00:00,Effect Monster

### Need to rethinking how I merge, since I still want the price data from full too, even if the sets data doesn't have it